### ISSUE TITLE
formatting issues

### ISSUE THREAD

**Issue by parasg1999** [validatorjs/validator-deno#15]
@rubiin We need a way to the maintain the format of the code. Changing tabs/spaces to each other creates large unnecessary diffs and I think our editor configuration is playing a role here.

**Comment by rubiin** [comment]
before pushing any changes do deno fmt. That should fix the formatting issue

**Comment by parasg1999** [comment]
Thanks, I will write that in contributing guide and then close this!

**Comment by rubiin** [comment]
sure
