### ISSUE TITLE
Reference in deno website

### ISSUE THREAD

**Issue by parasg1999** [validatorjs/validator-deno#2]
@rubiin 
I was wondering if this repository could be added to the deno website along with the word "official" in the description. Serves people in looking for what they need.

**Comment by rubiin** [comment]
yes that can be done

**Comment by parasg1999** [comment]
@rubiin Shall I open a PR in the repository?

```javascript
"validator-deno": {
    "type": "github",
    "owner": "validatorjs",
    "repo": "validator-deno",
    "desc": "The official port of validator.js for Deno"
  },
```

**Comment by rubiin** [comment]
@parasg1999 yeah sure. Do that

**Comment by parasg1999** [comment]
@rubiin Had to change the name to `validator_deno` since - isn't an allowed character there
.

**Comment by rubiin** [comment]
@parasg1999 check this too https://github.com/validatorjs/validator-deno/issues/3
