### ISSUE TITLE
Track progress

### ISSUE THREAD

**Issue by rubiin** [validatorjs/validator-deno#3]
This is used to track all the validators that has been ported successfully . Feel free to send in any PR which ports the validators which are not ticked below
- [x] isAfter
- [x] isAlpha
- [x] isAlphanumeric
- [x] isAscii
- [x] isBIC
- [x] isBase32
- [x] isBase64
- [x] isBefore
- [x] isBoolean
- [x] isBtcAddress
- [x] isByteLength
- [x] isCreditCard
- [x] isCurrency
- [x] isDataURI
- [x] isDate
- [x] isDecimal
- [x] isDivisibleBy
- [x] isEAN
- [x] isEmail
- [x] isEmpty
- [x] isEthereumAddress
- [x] isFQDN
- [x] isFloat
- [x] isFullWidth
- [x] isHSL
- [x] isHalfWidth
- [x] isHash
- [x] isHexColor
- [x] isHexadecimal
- [x] isIBAN
- [x] isIP
- [x] isIPRange
- [x] isISBN
- [x] isISIN
- [x] isISO31661Alpha2
- [x] isISO31661Alpha3
- [x] isISO8601
- [x] isISRC
- [x] isISSN
- [x] isIdentityCard
- [x] isIn
- [x] isInt
- [x] isJSON
- [x] isJWT
- [x] isLatLong
- [x] isLocale
- [x] isLowercase
- [x] isMACAddress
- [x] isMagnetURI
- [x] isMimeType
- [x] isMobilePhone
- [x] isMongoId
- [x] isMultibyte
- [x] isNumeric
- [x] isOctal
- [x] isPassportNumber
- [x] isPort
- [x] isPostalCode
- [x] isRFC3339
- [x] isRgbColor
- [x] isSemVer
- [x] isSlug
- [x] isSurrogatePair
- [x] isURL
- [x] isUUID
- [x] isUppercase
- [x] isVariableWidth
- [x] isWhitelisted

---
### Won't work on
- isLength  (deprecated)
- isMD5 (won't include)

**Comment by rubiin** [comment]
@parasg1999 pick the undone validators from here

**Comment by parasg1999** [comment]
@rubiin Sure! Will do. Was working on improving the test template.

**Comment by parasg1999** [comment]
I think we should remove `isMD5`, since `isHash` can be used with `md5` as the second argument.

**Comment by rubiin** [comment]
> I think we should remove `isMD5`, since `isHash` can be used with `md5` as the second argument.
> Also we are not trying to make it backwards compatible.

sure. Also we need to import any bug fixes from validator.js after we have ported the lib

**Comment by RishabAgarwal** [comment]
Hey, can I also work on this??

**Comment by rubiin** [comment]
@RishabAgarwal  sure.

**Comment by rubiin** [comment]
@parasg1999 lets speed up things as only 14 extra validators are needed to complete the lib

**Comment by RishabAgarwal** [comment]
Thanks @rubiin. I started working on isDivisibleBy. I was wonder if (1.2, 0.2) should return true or false?
Validator for nodejs returns false but in actual it is divisible.

**Comment by parasg1999** [comment]
> Thanks @rubiin. I started working on isDivisibleBy. I was wonder if (1.2, 0.2) should return true or false?
> Validator for nodejs returns false but in actual it is divisible.

@RishabAgarwal validator.js only works for integers, we can include the support for float as well. 
What do you say @rubiin

**Comment by RishabAgarwal** [comment]
I created  a PR for isDivisibleBy. I think we can add that later on.

**Comment by RishabAgarwal** [comment]
Hey, so should just add more validator to the master branch, the same PR #21 or create a new branch and a PR for every new validator??

**Comment by rubiin** [comment]
@RishabAgarwal  you can do either way

**Comment by RishabAgarwal** [comment]
I'll take isURL if no is doing it.

**Comment by rubiin** [comment]
sure

**Comment by RishabAgarwal** [comment]
I'll take up isEmail if no one is doing it

**Comment by parasg1999** [comment]
Go ahead! @RishabAgarwal

**Comment by rubiin** [comment]
@RishabAgarwal @parasg1999  lets work on documentation now

**Comment by RishabAgarwal** [comment]
Yeah sure. How do you wanna distribute it @rubiin

**Comment by rubiin** [comment]
@RishabAgarwal you can do any and as much you like. theres no restrictions

**Comment by RishabAgarwal** [comment]
@rubiin I'll get on it. Can you also add a check box list to the document issue too.

**Comment by parasg1999** [comment]
@RishabAgarwal I have added that.
