### ISSUE TITLE
isCreditCard refractoring

### ISSUE THREAD

**Issue by parasg1999** [validatorjs/validator-deno#5]
@rubiin I think we should reconsider _isCreditCard_ method and rename it to _isPayCard_ since it is impossible to tell the card type using number without using any APIs which is out of the scope of this library.

**Comment by rubiin** [comment]
Lets keep it on a discussion

**Comment by parasg1999** [comment]
In the validator.js repository, they have decided not to rename the method. So maybe we can close it for now to maintain consistency.

**Comment by rubiin** [comment]
sure. Closing it on the favor of the comment
