### ISSUE TITLE
Overwrite isJWT?

### ISSUE THREAD

**Issue by parasg1999** [validatorjs/validator-deno#7]
@rubiin I added isJWT but I think you have accidentally overwritten that when merging. The implementation was changed. Please confirm.

**Comment by rubiin** [comment]
@parasg1999 it was intentional. I implemented the original implementation of isJWT from validatorjs so as to prevent any future issues

**Comment by rubiin** [comment]
https://github.com/validatorjs/validator-deno/issues/8 in the mean time can you look into this?
